{% set name = "rsconnect-python" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rstudio/rsconnect-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 54e69aa16305c5dc60787b6bbde7ce3da9363b8635dca826cbfd8279cf7a4977

build:
  noarch: python
  entry_points:
    - rsconnect = rsconnect.main:cli
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - six >=1.14.0
    - click >=7.0.0
    - pip >=10.0.0  # rsconnect-python invokes pip as a subprocess

test:
  imports:
    - rsconnect

about:
  home: https://github.com/rstudio/rsconnect-python
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: 'The rsconnect-python CLI and library'

extra:
  recipe-maintainers:
    - bcwu
